### ISSUE TITLE
I cant add any-coin on portfolio page. 

### ISSUE THREAD

**Issue by Renaenys** [dziungles/Coinwink#12]
I cant add any coin into the PORTFOLIO

Add your first coin using the 'plus' button below. 

To remove the added coin, select it in the dropdown list and click the 'minus' button.
________________________________________ 

Add or remove coin:

nothing appeared. 

  When selecting the drop down box it shows "Searching" but nothing happen

**Comment by giekaton** [comment]
Hey @CryptoBeginner. Can you write how you solved this and why didn't it work in the first place? Thanks.

**Comment by Renaenys** [comment]
I was dumb as i forgot to run the http://mydomain.com/backend_backend_email.php before start to use =)

**Comment by giekaton** [comment]
Thanks for letting me know.
