### ISSUE TITLE
Help More Than Issue

### ISSUE THREAD

**Issue by rogueops** [dziungles/Coinwink#14]
What would be the simplest way to swap out the API used for another? I setup a personal version on a RPi and need it to use my exchanges API instead. I tried just swapping it out.

**Comment by giekaton** [comment]
The API connection is in the backend_email.php, starting at the line 22, but it is tightly coupled with the app and the database, so to swap the API would be complicated. Also depends how similar your exchange API is to the current CMC API.

It's an interesting use case - to swap the paid CMC API with some different API. In the future I'm thinking to create a coinwink-light, which would be more simple to use and modify (e.g. swap the API). Already started, but now busy with other projects, so not sure when I have time to finish the coinwink-light.

**Comment by rogueops** [comment]
From what I saw i figured it was complicated since the API output from my
exchange only outputs 1 with the same name. I am running into one issue
when using a cronjob to run backend email i get errors on the server side
and it does not update. I run it in my browser and that works just fine so
I guess I am asking what cronjob details should I be using?

**Comment by rogueops** [comment]
Sorry forgot to include the errors, it is throwing:

PHP Notice:  Undefined variable: alerts in

81
365
484
603
720
839

backend_email.php

Running it with php script.php

**Comment by giekaton** [comment]
Hi, in general "alerts" variable supposed to be an array of user created alerts, taken from the database. There shouldn't be a difference between running a script in your browser, or with a cron.

**Comment by rogueops** [comment]
When using browser no errors, just the run time and memory usage, but that
may be due to server setup, when running CLI it always outputs the exact
same every time, same with cron if you dont pipe it to null, I can post the
text it outputs or a screen shot if you like. I know WP uses a web cron and
not a system cron job so I may look into having the script run that way
instead.

**Comment by rogueops** [comment]
I just added quiet to the running of the script as I did not want to alter
the WP web cron job just yet, that makes the output the same as browser.

**Comment by rogueops** [comment]
Need just a little more help on a edit I am stuck on as I am a PHP beginner, I would like to just have the USD price showing on the email and percentage screens, logged in or not logged in, I have tried on my own and just cant get the "ICON = 0.03429142 BTC | 1 ETH |" to go away and just have the USD displayed, i can get the whole line to go be hidden, but seem to cant figure out how to just remove the 2 sections listed above. I thought I located the code in the .js and homepage-template file and edited the lines, but nothing happens.

**Comment by giekaton** [comment]
Sorry, it's an old release, I'm not supporting it any longer. I'm planning to update it with the lightweight version of Coinwink. It will be more flexible to use, and easy to learn from.

**Comment by rogueops** [comment]
I already got it
