### ISSUE TITLE
Feature request: TokenSet prices to watch

### ISSUE THREAD

**Issue by neuromancer** [dziungles/Coinwink#17]
[TokenSet](https://www.tokensets.com/) offers a large variety of "sets": digital assets (ERC-20) that represents a fully collateralized portfolio of other crypto-assets.

Is it possible to add these as coins to watch?

Thanks!

**Comment by giekaton** [comment]
Hey! 

Coinwink is using CoinMarketCap for the crypto market data. Just last week, additional 1000 coins were added to Coinwink, so now Coinwink tracks not 2600 but 3600 top CMC coins.

To answer your question: If these "sets" are presented as crypto assets and are available on CMC among other coins, they should automatically appear on Coinwink. If they are not on CMC, they are also not available on Coinwink.

**Comment by neuromancer** [comment]
It seems that [tokensets are almost all supported in CMC](https://coinmarketcap.com/exchanges/tokensets/). A few are missing, but I will ask them directly to support them. Thanks for the quick response!

**Comment by giekaton** [comment]
The link is for the `/exchanges` listing. That's a different one.

For coins to be available on Coinwink, they need to be in the `/currencies` listing.

**Comment by giekaton** [comment]
And for assets, I see that they are available under `/currencies` but there is a label "This listing is not eligible for normal ranking."
