### ISSUE TITLE
Stuck on loading...

### ISSUE THREAD

**Issue by kpdillon** [dziungles/Coinwink#18]
Everything installed OK, I followed the instructions but when I load the page instead of the coin list loading (below the coins to watch field) it is just stuck on the word "loading...."

**Comment by giekaton** [comment]
First of all, check if your database login details are correct in the `auth_sql.php` file. Also, check if your database `cw_data_cmc` table has data in it.

If it's still stuck on loading, check the browser's console if there are any error messages.

**Comment by kpdillon** [comment]
Yes, I do have this set correctly I believe.  the cw_data_cmc table is in fact empty.  

$cw_env = "live";
$servername = "XXX";
$username = "XXX";
$password = "XXX;
$dbname = "XXX";

Per the instructions below am I supposed to add my API key to the auth_sql.php file?  When I run the update, this is the only output I get:

Memory used: 24.2 mb
Execution time: 0.4319121837616 secroot

**Comment by kpdillon** [comment]
I do see these errors

Access to internal resource at 'https://coinwink.com/img/favicon/site.webmanifest?v=2bBgz68qw' from origin '' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

DevTools failed to load SourceMap: Could not load content for http://XXX/wp-content/themes/coinwink-theme/js/navigo.min.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://XXX/wp-content/themes/coinwink-theme/js/html5sortable.min.js.map: Load canceled due to load timeout

**Comment by kpdillon** [comment]
Looks like I got it to work.  I must have had some kind of typo in the headers.php file.

**Comment by MongoRanger** [comment]
I am having this same issue.  I verified info in auth_sql.php.  I checked the cw_data_cmc table and there does appear to be data in it.  I get the same console errors as above.

When I go to mycoinwinkdomain.com/btc then it works and the list shows up.
The list does not show up on the portfolio or watchlist pages either unless I start with /btc (or another coin) to get the list to come up then it is there if I go to the portfolio or watchlist.

**Comment by giekaton** [comment]
Did you do this from the readme: Set the `homePath` variable to your Wordpress location in the theme's `header.php` file.

**Comment by MongoRanger** [comment]
Yes I did, line 644 now looks like this (with the correct domain name)
`homePath = "https://MYDOMAIN.com/";`

**Comment by giekaton** [comment]
And the placeholder `https://MYDOMAIN.com/` is the correct URL where the Coinwink home page should be loaded?

Do you see any error messages in the console (F12), when the list doesn't load?

**Comment by MongoRanger** [comment]
I sent you an email with specifics if that helps.

**Comment by giekaton** [comment]
Hi, after thinking a little bit more about this, I spotted the issue.

If you are hosting Coinwink in the subfolder of a domain (e.g. `https://MYDOMAIN.com/coinwink`), then everything should work fine by default.

But if you are hosting it on the root domain (e.g. `https://MYDOMAIN.com/`), then you should uncomment `coinwinkEnv = 'live';` on line 640 and then edit the `homePath` on line 647 `homePath = "https://MYDOMAIN.com/";`

Let me know if it works now!

**Comment by MongoRanger** [comment]
I tried that and there were still issues so I ended up starting fresh and
using a subfolder.  Everything seemed to be working fine until I ran
"cron_data_cmc.php" in the address bar to update for the first time.  I see
where the query completed, but after that all of the coins in the portfolio
and watchlist I entered disappeared and the list no longer shows up.  I
checked the DB and it did update cw_data_cmc.

**Comment by giekaton** [comment]
Hi, before running `cron_data_cmc.php`, you need to update `auth_cmc.php` with your CoinMarketCap API key. You can register for a free API key here: https://pro.coinmarketcap.com/

**Comment by MongoRanger** [comment]
I did that, CoinMarketCap even showed the credits used and the logged
query.  I checked the DB and it was updated.

Thank you for working with me on this.

**Comment by giekaton** [comment]
Good to know that you got the API key.

I guess this can be related to the recent "τBitcoin" special character issue.

Try inserting the following lines to your `cron_data_cmc.php` after line 48 (starts with $output...) and before line 50 (starts with $outputdecoded) and run the script again. I have not commited this fix to the repo yet.

```
    $output = str_replace("τBitcoin", "tBitcoin", $output);
    $output = str_replace("ΤBTC", "TBTC", $output);
```

**Comment by MongoRanger** [comment]
So here are lines 47 through 52.  It seems to have fixed it!
```
else {
	// Remove possible single quotes from JSON string and decode
	$output = str_replace("'", "", $response);
	$output = str_replace("τBitcoin", "tBitcoin", $output);
	$output = str_replace("ΤBTC", "TBTC", $output);
        $outputdecoded = json_decode($output, true);
```

**Comment by giekaton** [comment]
You may want to pull the updated source code of this repository. In the newest coin data array from CMC, there are more special characters, so I added a universal fix for such cases (using json_encode/decode instead of serialize/unserialize), and then you don't need to manually do `str_replace` as in the previous comment.
