### ISSUE TITLE
Issue with Email

### ISSUE THREAD

**Issue by kpdillon** [dziungles/Coinwink#19]
I can get email plugins to work but I believe with PHP 7 something change and this code is not working with coinwink.

PHP Fatal error:  Cannot declare class PHPMailer\\PHPMailer\\PHPMailer, because the name is already in use in /home/crypto/wp-includes/PHPMailer/PHPMailer.php on line 32,

**Comment by giekaton** [comment]
Maybe you are using an older version of this source code? The latest commit (12 days ago) updated the PHPMailer.

Check if the beginning of your `auth_email.php` file is similar as here: https://github.com/coinwink/Coinwink/blob/master/auth_email.php

Also, your need `/lib/PHPMailer/` package, which was added to this repo with the latest commit.

**Comment by arch-btw** [comment]
@giekaton sorry to bother you again but I'm having the same issue.

Anytime I try to do anything in wordpress that triggers an email I get the above error.

I'm using the latest source code of coinwink and also tried updating PHPMailer to PHPMailer-6.4.1.

The email report that wordpress is supposed to send doesn't arrive either.

![error](https://user-images.githubusercontent.com/57669023/119497903-ed6b5b00-bd19-11eb-931c-6fb85b2e817b.png)

Hope you can help :-)

**Comment by arch-btw** [comment]
I'm using PHP 7.4 by the way.

**Comment by giekaton** [comment]
Hi,

Please try insering the SMTP line in your auth_email.php file, after the 4th line, so it will look as below:

use PHPMailer\PHPMailer\PHPMailer;
**use PHPMailer\PHPMailer\SMTP;**
use PHPMailer\PHPMailer\Exception;

Let me know if this fixed the issue. If not, I will take a better look at it.

**Comment by arch-btw** [comment]
Hi, Thank you,,
Unfortunately that didn't work. It's still producing the same error message.

**Comment by arch-btw** [comment]
I should add that the emails from coinwink itself do work. It's just that it disabled all the wordpress emails from working.

**Comment by giekaton** [comment]
I have updated the `auth_email.php` file in the latest commit. Check it out and let me know if it works now. The error that you have mentioned is gone, but I'm not sure if WP sends emails now - maybe this PHPMailer version needs some additional configuration.

**Comment by arch-btw** [comment]
Wow thank you so much, that did get rid of the error message indeed!
That being said, it's like you said, it still doesn't send emails from wordpress.
I tried setting:
$mail->SMTPDebug = 2;
But I can't figure out where it's sending the log.
There's an admin email at the bottom to receive error logs but you guessed it, it's not receiving any emails haha.

**Comment by arch-btw** [comment]
Ok I got a little further.

So the two error messages when sending email in wordpress are:

Message could not be sent.Mailer Error: You must provide at least one recipient email address.

And

Message could not be sent.Mailer Error: Message body empty

So when I add:

$mail->addAddress('my@email.com');
$mail->Body = 'Testing';

To: auth_email.php

Then the wordpress emails work.
The problem with this is that both variables are now static.
Meaning, the content of every wordpress email is now "testing" as opposed to the actual message.
And they are all sent to the same address that I filled out above.

I'm not sure how to proceed.

**Comment by arch-btw** [comment]
This is how I captured the error messages (by adding this to auth_email.php) :


if(!$mail->send()){
    echo 'Message could not be sent.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}else{
    echo 'Message has been sent';

Keep in mind that due to wordpress's admin top bar, the error messages are hidden behind it. So I did select all on the page and copied all the text to a text editor.

**Comment by giekaton** [comment]
Thanks for this extra info. Email configuration can be tricky sometimes. I'm still not sure where is the issue, but I'll keep looking and update you here when I have more details.

**Comment by arch-btw** [comment]
Thank you giekaton, I really appreciate your help!

**Comment by giekaton** [comment]
The issue is now fixed!

1. PHPMailer must be passed as `( $phpmailer )`
2. You need to update `YOUR_EMAIL_ADDRESS` and `YOUR_WEBSITE_NAME` variables.

Also, Coinwink now supports PHP8 and the latest WP version.

**Comment by arch-btw** [comment]
Thank you @giekaton , so happy with this project, I use it every day!
