### ISSUE TITLE
Sends unique ID with alert but then ID does not exist when managing alerts

### ISSUE THREAD

**Issue by ricardoschiller** [dziungles/Coinwink#2]
I requested an alert, received it with my unique ID. Couldn't enter the manage alerts area with the ID send. It says it doesn't exist...

**Comment by giekaton** [comment]
Hey, this actually works as supposed.

When your last active alert was sent, it was automatically deleted and with it your ID is also deleted. This is done for the sake of users' privacy.

When you create a new alert with the same email, you will receive the new ID. It will work as long as you have active alerts.

I consider changing this functionality in the future...
