### ISSUE TITLE
Errors reference cron_alerts_email_cur.php

### ISSUE THREAD

**Issue by MongoRanger** [dziungles/Coinwink#20]
I am getting these errors in the log:
```
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 341
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 342
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 343
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 344
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 345
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 346
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 347
PHP Notice:  Trying to access array offset on value of type null in /home/markzerb/public_html/Coinwink/cron_alerts_email_cur.php on line 348
```

**Comment by giekaton** [comment]
Are you using the latest source code from this repository? It was updated a few days ago.

**Comment by MongoRanger** [comment]
Yes, I am, I updated all the files.

As far as I can tell it looks like those lines are trying to pull data from the database and reference currency rates.  I already set up both A and B API keys in cron_data_cur_rates.php and ran the job which came back with this.
`PLAN A -> EUR:0.82579 GBP:0.719445 CAD:1.24585 AUD:1.286687 BRL:5.47875 MXN:19.81099 JPY:107.735989 SGD:1.325805`
When I check the database that data is not in the cw_data_cur_rates table.

Since there is no data in the table and cron_data_cur_rates.php is trying to UPDATE the information I ran this command in the database:
`INSERT cw_data_cur_rates SET ID = 1, EUR = 0.82579, GBP = 0.719445, CAD = 1.24585, AUD = 1.286687, BRL = 5.47875, MXN = 19.81099, JPY = 107.735989, SGD = 1.325805`
Now since there is data there, cron_data_cur_rates.php will be able to update it next time it runs and cron_alerts_email_cur.php has data to pull which I am thinking will take care of the errors.

**Comment by giekaton** [comment]
Thanks for pinpointing the issue and for the update.

It seems that the script gets prices correctly, but doesn't update the database.

I guess you have edited the `auth_sql.php` file with the correct database login details?

**Comment by MongoRanger** [comment]
Yes, auth_sql.php has the correct details.  You're correct that the script get the prices correctly but it can not update the database because there is nothing there to update.  Since I inserted the data the database has updated without issue when cron_data_cur_rates.php runs and there have been no more errors.

**Comment by giekaton** [comment]
What do you mean by "there is nothing there to update"?

`cron_data_cur_rates.php` script should update the `cw_data_cur_rates` table with the currency rates from the API, as in line 58.

**Comment by giekaton** [comment]
Ah, got it. I guess, after the initial Coinwink setup, the `cw_data_cur_rates` table has no example data in it, and that's why later the script cannot update the record. If that's correct, then I will update the activation script, so that it would include initial currency rates.

**Comment by MongoRanger** [comment]
You got it, there has to be something there already for the UPDATE command
to work.

**Comment by giekaton** [comment]
Updated the activation script with example data for currency rates. Now this issue should not re-appear.
