### ISSUE TITLE
Can't get it to work. Page stuck at "Searching".

### ISSUE THREAD

**Issue by arch-btw** [dziungles/Coinwink#21]
Hi,

Thank you for this project.

I've been trying to get this to work on my own domain but it's not working.
I was hoping for your help.
Here's what I've tried to fix it so far:

- Put the correct information in auth_sql.php
- Put the homePath in header.php (https://redacted.com/coinwink/)
- Tried both dev and live in auth_sql.php
- Verify that data is in the database.
- Put API key in auth_cmc.php
- Run cron_data_cmc.php (this does seem to succeed).
- Reinstall in coinwink subfolder as per https://github.com/coinwink/Coinwink/issues/18

I'm at a loss here.
Here are the errors that I'm getting:

![2021-05-23_16-23](https://user-images.githubusercontent.com/57669023/119279927-7633ab00-bbe3-11eb-9ba8-80898166f2c2.png)

Here's my database:

![2021-05-23_16-27](https://user-images.githubusercontent.com/57669023/119279976-d32f6100-bbe3-11eb-9816-35589ca67dd6.png)

Thank you.

**Comment by arch-btw** [comment]
Ok I fixed it.

Just in case someone has the same issue:
I didn't realize coinwink's database has to use the same database as wordpress.
I created a seperate database for coinwink and that's where it went wrong.
Also, simply changing the database later didn't work, because coinwink generates the database just once.
When I started from scratch with the wordpress database it worked.

Thank you!

**Comment by giekaton** [comment]
It's good to hear that you have sorted this out. And thanks for explaining the issue for others. Good luck!
