### ISSUE TITLE
Please format your code

### ISSUE THREAD

**Issue by jurij** [dziungles/Coinwink#7]
Example:

https://github.com/dziungles/Coinwink/blob/master/script-files/backend.php

Cant read code because brackets

**Comment by dziungles** [comment]
Hi. Soon this code will be rewritten to optimize the processing.

Can you please elaborate, what do you mean by "I can't read code because of brackets"?

**Comment by giekaton** [comment]
At the moment this particular part of code is being rewritten to optimize the processing. When finished, I will also improve the general formatting, and update the repo.

**Comment by giekaton** [comment]
Done. Code optimized and properly formatted.
