### ISSUE TITLE
Suggestion: Volume

### ISSUE THREAD

**Issue by ankitydv193** [dziungles/Coinwink#8]
Can you add another indicator for Volume increase/decrease by n%

**Comment by giekaton** [comment]
I think this will be implemented pretty soon. Today I have added support for all CMC coins. Also need to add more currencies. Then maybe the volume alerts. Thanks for suggestion.

**Comment by ankitydv193** [comment]
Thanks! 👍 
This is the best alert system out there. 
Only important stuff without any unnecessary added stuff!

**Comment by giekaton** [comment]
Thanks for the feedback :)
