### ISSUE TITLE
Email address [Suggestion]

### ISSUE THREAD

**Issue by ankitydv193** [dziungles/Coinwink#9]
So I have made an account on the site but even now when I try to make a new alert, form asks to enter the email id every time. 
Can you add auto-fill of email for registered users? 
Thanks.

**Comment by giekaton** [comment]
I guess it saved the email after the page reload? I may implement this through ajax later, so that the saving shouldn't require the reload.

**Comment by ankitydv193** [comment]
It didn't the first few times I reloaded the page but it autofilled after I closed my browser and reopened it. Don't know why though.

**Comment by giekaton** [comment]
I will improve this when have some more time. The UI shouldn't have any "bumps" for the user.

**Comment by ankitydv193** [comment]
Nice. I will think of some idea to improve and suggest you or make a pull request if I will be able to code it.

**Comment by giekaton** [comment]
Just keep in mind that the code here is not recent. I am currently adding new features and doing optimization. As soon as I finish this, I will update the repo. That's probably sometime next month. Your ideas are always welcome.

**Comment by ankitydv193** [comment]
How about adding an option to edit alerts? Right now we have to delete and add new one.
